version: '3'

services:
  build:
    build:
      context: .
      dockerfile: dockerfiles/build
    volumes:
      - .:/code

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./data/:/var/lib/mysql
    restart: always

  tphbot:
    depends_on:
      - db
      - build
    build:
      context: .
      dockerfile: dockerfiles/tphbot
    volumes:
      - ./config/:/tphbot/config
    restart: always
