version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: tphbot
      MYSQL_USER: tphbot
      MYSQL_PASSWORD: tphbot
      MYSQL_ROOT_PASSWORD: tphbot_root

  tphbot:
    depends_on:
      - db
    build: .

volumes:
  db_data: {}